#!/usr/bin/env bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
PATTERN="^feat/"

echo $INPUT_FILE
echo $START_LINE

if [[ "$START_LINE" =~ $PATTERN ]]; then
  yarn nx affected --target=version --all
  exit 0
fi